### ISSUE TITLE
[New Block] Copyright Footer Info

### ISSUE THREAD

**Issue by pawelmadeja** [wpserved/astratic-blocks#11]
Whole idea for a block is dead simple. We need a block that will print such information:
`©` `{Current Year}` `{Website Name}`

for example:
`© 2022 Astratic`

So we could simply place it in a website footer.

**Comment by coditive-filip-c** [comment]
![ab-icon-footer-copyright](https://user-images.githubusercontent.com/108737316/177328611-d8127f7b-9f97-4a06-9557-a2e1d858f2c9.svg)

**Comment by coditive-pawel-m** [comment]
Implemented in v1.5.0
