### ISSUE TITLE
Hide Base block

### ISSUE THREAD

**Issue by coditive-pawel-m** [wpserved/astratic-blocks#9]

**Comment by coditive-przemek-h** [comment]
I think that we can remove initialization [here](https://github.com/wpserved/astratic-blocks/blob/main/src/Blocks/Blocks.php#L14).

**Comment by coditive-michal-k** [comment]
Thank you @coditive-przemek-h for your feedback. I've removed this line. The newest release and version of the plugin (1.1.1) has been published https://pl.wordpress.org/plugins/astratic/
